Enable automatic IAM database authN for Cloud SQL
petoju/terraform-provider-mysql pull request #109
Opened 2024-01-30 13:12 UTC by rialg

* Add `iam_database_authentication` option in the provider to switch on/off IAM authN
* If `iam_database_authentication`, the `password` field will be a temporary access token. The implementation follows the example made in [the documentation](https://cloud.google.com/sql/docs/mysql/iam-logins#log-in-with-automatic).

2024-01-30 16:27 UTC, petoju commented
This looks good, but you have conflict in mysql/provider.go

2024-01-31 07:39 UTC, rialg commented
@petoju thanks for the swift response. I had resolved the merge conflict. Could you take another look? :)

2024-01-31 21:19 UTC, petoju requested changes
Just one typo - it looks good otherwise (I did not try it, but we can try it then).

2024-01-31 21:19 UTC, petoju commented on website/docs/index.html.markdown
> +* `iam_database_authentication` - (Optional) For Cloud SQL databases, it enabled the use of IAM authentication. Make sure to delcare the `password` field with a temporary OAuth2 token of the user tha
```suggestion
* `iam_database_authentication` - (Optional) For Cloud SQL databases, it enabled the use of IAM authentication. Make sure to declare the `password` field with a temporary OAuth2 token of the user that will connect to the MySQL server.
```

2024-02-01 16:52 UTC, petoju approved these changes

2024-02-01 16:53 UTC, merged

2024-02-01 16:58 UTC, petoju commented
@rialg  thanks!
It's now in 3.0.47