Add table data source documentation
petoju/terraform-provider-mysql pull request #44
Opened 2022-11-06 09:17 UTC by Ken-Sumi1019

2022-11-06 18:19 UTC, petoju requested changes
Thanks, it mostly looks good - I have only some grammar issues / extra newline / type.

2022-11-06 18:19 UTC, petoju commented on website/docs/d/tables.html.markdown
> +  Get tables on a MySQL server.
Just nit-picking: please add "s" as it's 3rd person singular. So it `gets` tables from a MySQL server.

The same issue is with description a bit lower

2022-11-06 18:19 UTC, petoju commented on website/docs/d/tables.html.markdown
> +
Maybe the newline here is not necessary.

2022-11-06 18:19 UTC, petoju commented on website/docs/d/tables.html.markdown
> +* `tabels` - The list of the table names.
```suggestion
* `tables` - The list of the table names.
```

2022-11-06 23:40 UTC, Ken-Sumi1019 commented
Thanks for your review.
I have corrected everything.

2022-11-07 08:10 UTC, petoju commented
Thanks for the fixes.

2022-11-07 08:11 UTC, merged