feat: add retain old password support
petoju/terraform-provider-mysql pull request #90
Opened 2023-09-12 09:10 UTC by Kiliandeca

Hello :wave:, this PR introduce the possibility of retaining the old password when the password change as described in https://github.com/petoju/terraform-provider-mysql/issues/17.

I would like to add a test but I'm not very fluent in Go and unless I'm mistaken there are currently no test that check if the user password works from which I could copy/inspire. Any feedback or advice is very welcome :pray:

2023-09-12 20:54 UTC, petoju requested changes

2023-09-12 20:54 UTC, petoju commented on mysql/resource_user.go
> +			return diag.Errorf("%v", err)
Please make error message more descriptive by saying, where it came from.
Go usually goes with "stacktrace-like" errors, where more and more errors are prepended to the error message. That makes debugging easier.

2023-09-12 20:54 UTC, petoju commented on mysql/resource_user.go
> +func checkRetainCurrentPasswordSupport(ctx context.Context, meta interface{}) (bool, error) {
Consider returning just `bool` or just `error`.
It seems you never use the `bool` output, so maybe it is useless?

2023-09-12 20:54 UTC, petoju commented on mysql/resource_user.go
For tests:

implement your own check similar to this one
https://github.com/petoju/terraform-provider-mysql/blob/master/mysql/resource_user_test.go#L151-L181
that will check, whether one can authenticate as given user with given password. Maybe your test will just try to connect to MySQL with that data.

Then implement test like this:
https://github.com/petoju/terraform-provider-mysql/blob/master/mysql/resource_user_test.go#L54-L89
you don't have to run TestCheckResourceAttr. Without that, you'll run some written config, then possibly do some check. Next step will change password by specifying another config and run the check again to verify the old password stayed in place.
The last step would be to check, whether authentication with some random password works - that is a verification whether our tests make sense.

I also recommend doing test for the case one doesn't want to retain password.

2023-09-14 12:54 UTC, Kiliandeca commented
Thanks for your quick review and guidance on how to implement the tests. Let me know if there are still things you want me to improve.

2023-09-14 17:08 UTC, petoju approved these changes
Looks good!

2023-09-14 17:11 UTC, merged

2023-09-14 17:41 UTC, petoju commented
Released in v3.0.42